### PR TITLE
Fix for negative JoJc error

### LINKED ISSUE #158: Invalid cost function in 3DVar test negative JoJc
## Description

https://github.com/JCSDA-internal/oops/pull/3054#issuecomment-3397416786

The above change unearthed an error in one of our tests (`test_orcamodel_3DVar_sic`).
 
For now we will comment out this test, but for it to be useful we should understand the issue and come up with a proper fix.

### PR DESCRIPTION
**Pull request by frld**
## Description

This fix involves updating increment copy to copy fields  rather than references which was causing different variables to become linked together. This fixes the negative JoJc error  that we saw in the (standard) 3DVar test ever since the check was added to OOPS. As it now works I have reactivated the 3DVar test.

## Issue(s) addressed

Resolves #158

## Dependencies

List the other PRs that this PR is dependent on:
- None

## Impact

Expected impact on downstream repositories or workflows: None

## Checklist

- [x] I have updated the unit tests to cover the change
- [x] New functions are documented briefly via Doxygen comments in the code
- [x] I have linted my code using cpplint
- [x] I have run the unit tests
- [x] I have run mo-bundle to check integration with the rest of JEDI and run the unit tests under all environments

### CODE REVIEW

**Comment by frld** [comment]
Surprisingly it didn't change the results much (on the first iteration). I think the problem was mainly affecting diagnostic variables and the setup for the next iteration of the cost function minimisation which previously gave NaNs. With this fix I can now run more than one iteration so I have changed the test yaml files to have two iterations (to keep the tests cheap).

Here's some increments

3DVar B identity:
fldplot_incs1

3DVar B using BUMP:
fldplot_incs2

**Comment by frld** [comment]
All the ctests including unit tests pass. I'll have a look to see if it makes sense to add a unit test to catch this sort of issue.

**Comment by frld** [comment]
I added a unit test to check increment copies are independent.

**Comment by frld** [comment]
I've run the bbb tests. See https://cylchub/services/cylc-review/cycles/daniel.lea/?suite=mo-bundle-jojc-fix

All passed except for one unrelated failure in https://cylchub/services/cylc-review/taskjobs/daniel.lea?&suite=mo-bundle-jojc-fix&no_fuzzy_time=0&tasks=ctest_all_ufo__spice_gnu_debug :

[INFO] command: run-ctest-alls ufo -E 'coding_norm'
...
471/988 Test #479: ufo_reconditioning_within_group ..........................................................................***Failed    3.34 sec

File: src/orca-jedi/increment/Increment.cc [hunk 1]
```diff
@@ -635,6 +631,24 @@ void Increment::setupIncrementFields() {
...
+/// \param Source Atlas fieldset.
+/// \param Destination Atlas fieldset.
+void Increment::copyIncFieldSet(const atlas::FieldSet & source, atlas::FieldSet & dest) {
+  for (atlas::idx_t i=0; i < static_cast<atlas::idx_t>(vars_.size()); ++i) {
+    // copy variable from source to dest field set
+    atlas::Field field = source[i];
+    oops::Log::debug() << "Copying increment field " << field.name() << std::endl;
+    auto field_view_dest = atlas::array::make_view<double, 2>(dest[i]);
+    auto field_view_source = atlas::array::make_view<double, 2>(field);
+    for (atlas::idx_t j = 0; j < field_view_source.shape(0); ++j) {
```
Comment (odlomax) [inline src/orca-jedi/increment/Increment.cc]: You can replace this double loop with:

`field_view_dest.assign(field_view_source)`

Comment (odlomax) [reply src/orca-jedi/increment/Increment.cc]: For completeness, you should probably also add `dest[i].metadata() = source[i].metadata()` after the data copy.

**Review by odlomax — COMMENTED** [review]
Looks sensible enough. You can simplify the double loop in the field copy. It's probably worth copying the field metadata as well as the data. OOPS shouldn't be tinkering with it, but you never know...

**Review by twsearle — CHANGES_REQUESTED** [review]
Can you have a go at the changes Olly suggested please? I have completely lost confidence in the atlas assignments everywhere now! I hope I haven't made the mistakes elsewhere! As long as we don't need to worry about missing values we don't need to write the double loop ourselves and we are better relying on the newer atlas functionality.

File: src/orca-jedi/increment/Increment.cc (hunk 1 above)
Comment (frld) [reply src/orca-jedi/increment/Increment.cc]: Thanks. I've updated the code based on your suggestion. It looks a lot neater this way.

I reran the orca-jedi ctests and they all (29/29) pass.

**Comment by frld** [comment]
> Can you have a go at the changes Olly suggested please? I have completely lost confidence in the atlas assignments everywhere now! I hope I haven't made the mistakes elsewhere! As long as we don't need to worry about missing values we don't need to write the double loop ourselves and we are better relying on the newer atlas functionality.

Is this change good to go in now? As I said above I've made the change Olly suggested, it does look much neater, and I reran the ctests and can confirm all the tests still pass (with unchanged results compared the version with the explicit copy loop). I guess it would be good as a seperate piece of work to see if there is any where else where these generic routines can be implemented.

File: src/orca-jedi/increment/Increment.cc [hunk 2]
```diff
@@ -110,12 +99,19 @@ Increment::Increment(const Increment & other, const bool copy)
...
+  vars_ = other.vars_;
   geom_.reset();
-  geom_ = rhs.geom_;
+  geom_ = other.geom_;
+
+  incrementFields_ = atlas::FieldSet();
+
+  setupIncrementFields();
+
+  copyIncFieldSet(other.incrementFields_, incrementFields_);
```
Comment (odlomax) [inline src/orca-jedi/increment/Increment.cc]: Should be able to replace this with

```cpp
incrementFields_ = other.incrementFields_.clone();
```

File: src/orca-jedi/increment/Increment.h [hunk 3]
```diff
@@ -133,6 +133,7 @@ class Increment : public util::Printable,
 /// Data
  private:
   void setupIncrementFields();
+  void copyIncFieldSet(const atlas::FieldSet &, atlas::FieldSet &);
```
Comment (odlomax) [inline src/orca-jedi/increment/Increment.h]: Can remove this.

File: src/orca-jedi/increment/Increment.cc [hunk 4]
```diff
@@ -635,6 +631,20 @@ void Increment::setupIncrementFields() {
...
+  for (atlas::idx_t i=0; i < static_cast<atlas::idx_t>(vars_.size()); ++i) {
+    // copy variable from source to dest field set
+    oops::Log::debug() << "Copying increment field " << source[i].name() << std::endl;
+    auto field_view_dest = atlas::array::make_view<double, 2>(dest[i]);
+    auto field_view_source = atlas::array::make_view<double, 2>(source[i]);
+    field_view_dest.assign(field_view_source);
+    dest[i].metadata() = source[i].metadata();
+  }
+}
+
```
Comment (odlomax) [inline src/orca-jedi/increment/Increment.cc]: Should be able to remove this.

File: src/orca-jedi/increment/Increment.cc [hunk 5]
```diff
@@ -87,18 +87,7 @@ Increment::Increment(const Increment & other, const bool copy)
...
-      auto field_view = atlas::array::make_view<double, 2>(incrementFields_[i]);
-      auto field_view_other = atlas::array::make_view<double, 2>(field);
-      for (atlas::idx_t j = 0; j < field_view.shape(0); ++j) {
-        for (atlas::idx_t k = 0; k < field_view.shape(1); ++k) {
-          field_view(j, k) = field_view_other(j, k);
-        }
-      }
-    }
+    copyIncFieldSet(other.incrementFields_, incrementFields_);
   }
```
Comment (odlomax) [inline src/orca-jedi/increment/Increment.cc]: Should be able to replace this with:

```cpp
  if (copy) {
    incrementFields_ = other.incrementFields_.clone();
  } else {
    incrementFields_ = atlas::FieldSet();
    setupIncrementFields();
  }
```

**Review by odlomax — CHANGES_REQUESTED** [review]
Sorry to be a pain. I've had a deeper look at it, and I think there's more that can be done to tidy this up.

On the plus side, I've explicitly written the suggested changes for you!

File: src/orca-jedi/increment/Increment.cc (hunk 4 above)
Comment (frld) [reply src/orca-jedi/increment/Increment.cc]: No problems letting this go. One thing I didn't like was the use of the vars_ variable in the for loop, but with my limited atlas knowledge I wasn't sure how to get rid of this (and instead just loop through all the fields in the fieldset).

**Comment by odlomax** [comment]
> Can you have a go at the changes Olly suggested please? I have completely lost confidence in the atlas assignments everywhere now! I hope I haven't made the mistakes elsewhere! As long as we don't need to worry about missing values we don't need to write the double loop ourselves and we are better relying on the newer atlas functionality.

Hi @twsearle, @frld,

I appreciate this is a bit confusing. Essentially, all classes are implemented as shared pointers, so...

```cpp

Field A = atlas::Field{/*Some setup stuff*/};    // Create a field.
Field B = A;                                     // A.get() == B.get();
Field C = A.clone();                             // C is a new field with data and metadata copied from A.
```

The same logic can be applied to `FieldSets` too.


One thing to be aware of, reference counting on object handles is not thread-safe.
**Always** get objects by const reference if you don't intend to write to them.

```cpp

// Copies extracted field handle.
// This will mess up reference counting on extracted field in a parallel OMP region.
Field extract_some_field(const FieldSet& fset);

// Copies fset handle.
// This will mess up reference counting on fset in a parallel OMP region.
const Field& extract_some_field(FieldSet fset);
```

File: src/orca-jedi/increment/Increment.cc (hunk 4 above)
Comment (odlomax) [reply src/orca-jedi/increment/Increment.cc]: I think the `oops::Variables vars_` object is essentially a manifest of the fields that the increment cares about. I suspect it predates the adoption of Atlas. I believe the main data object in it is a `std::vector<std::string>`. tl;dr: copying it is probably a good idea. 🙂

**Comment by frld** [comment]
I've implemented the most recent suggestions of @odlomax  

All seems to work perfectly with the orca-jedi ctests all still passing.

**Review by odlomax — APPROVED** [review]
Sweet! The best lines of code are the ones you take away!

**Review by twsearle — APPROVED** [review]

**Comment by twsearle** [comment]
> > Can you have a go at the changes Olly suggested please? I have completely lost confidence in the atlas assignments everywhere now! I hope I haven't made the mistakes elsewhere! As long as we don't need to worry about missing values we don't need to write the double loop ourselves and we are better relying on the newer atlas functionality.
> 
> Hi Toby Searle (@twsearle), Daniel Lea (@frld),
> 
> I appreciate this is a bit confusing. Essentially, all classes are implemented as shared pointers, so...
> 
> ```c++
> Field A = atlas::Field{/*Some setup stuff*/};    // Create a field.
> Field B = A;                                     // A.get() == B.get();
> Field C = A.clone();                             // C is a new field with data and metadata copied from A.
> ```
> 
> The same logic can be applied to `FieldSets` too.

I am a bit confused on how this relates to the logic before the change in the PR. We were taking the references to the fields, and then operating on the field elements so I thought we would be OK! But somehow we were still referencing the same memory.

> One thing to be aware of, reference counting on object handles is not thread-safe. **Always** get objects by const reference if you don't intend to write to them.
> 
> ```c++
> // Copies extracted field handle.
> // This will mess up reference counting on extracted field in a parallel OMP region.
> Field extract_some_field(const FieldSet& fset);
> 
> // Copies fset handle.
> // This will mess up reference counting on fset in a parallel OMP region.
> const Field& extract_some_field(FieldSet fset);
> ```

Both these examples are bad? is there a thread safe way to do this? I am thinking about the norm calculation where I am considering just ripping out the OMP at this point (just a simple pragma my foot!). See this issue for context whcih might be related:
https://github.com/MetOffice/orca-jedi/issues/189

**Comment by frld** [comment]
Thank you both. Such a relief to get to the bottom of this even if it has made us a bit nervous about the possibility of similar problems lurking elsewhere.
