### PR TITLE
Interpolator mask

### LINKED ISSUE #95: Unexpected behaviour when using nearest neighbour time stepping
## Description

Nearest neighbour time-stepping seems to always use the last state in the list.

### PR DESCRIPTION
**Pull request by s-good**
## Description

The interpolator currently does not use the mask variable so it returns interpolated values when it shouldn't. In the case of nearest neighbour time interpolation, this results in the model value from the last time point always being returned.

## Issue(s) addressed

Resolves #95 

## Dependencies

None.

## Impact

Only affects JOPA runs where the model background has multiple time steps. The configuration files have recently been updated to all use linear interpolation so there will be no effect from this change.

## Checklist

- [x] I have updated the unit tests to cover the change
- [x] New functions are documented briefly via Doxygen comments in the code
- [x] I have linted my code using cpplint
- [x] I have run the unit tests
- [x] I have run mo-bundle to check integration with the rest of JEDI and run the unit tests under all environments: output can be seen at http://fcm1/cylc-review/taskjobs/hadgs/?suite=mo-bundle-orca_jedi_97.

### CODE REVIEW

**Comment by s-good** [comment]
I've tested the code on MetOp SST data using the sith suite and it appears to work. However, I'm not 100% confident I understand the way the mask variable is supposed to be used. @twsearle, please could you give an initial review and if you think it looks OK I will work on updating the unit test reference data.

**Comment by twsearle** [comment]
This looks correct to me - its slightly different from how others implement it in that we ensure the default value is always the missing data indicator, however I still think this lines up with the behaviour of the generic atlas interpolator here:
https://github.com/JCSDA-internal/oops/blob/c531e3fde8a313349f7a27f3da00f8719858ad00/src/oops/generic/AtlasInterpolator.cc#L53

**Comment by twsearle** [comment]
@odlomax Can you confirm this is the correct approach to implementing the oops interpolator "time mask" variable?

**Review by odlomax — APPROVED** [review]
Looks good to me.

**Comment by twsearle** [comment]
I think this is all good, and the reason the CI is failing is because the nearest-neighbour interpolation is used in our tests and is now giving a different result. I think this should be possible to fix by changing the dates on the various tests to match to the final state in the file. I will leave that to you to double check.

**Comment by twsearle** [comment]
Interesting that you saw a CPP lint issue that wasnt picked up by the CI? maybe somehow when you ran cpplint it didn't pickup the configuration file? Regardless it all looks great to me! Do you want to take it out of draft, I will review and we can get it merged up?

File: src/tests/orca-jedi/test_interpolator.cc [hunk 1]
```diff
@@ -114,7 +114,7 @@ CASE("test basic interpolator") {
   }
   SECTION("test interpolator.apply multiple levels") {
     std::vector<double> vals(nlevs*nlocs);
-    std::vector<bool> mask(nlevs*nlocs);
+    std::vector<bool> mask(nlocs, true);
```
Comment (twsearle) [inline src/tests/orca-jedi/test_interpolator.cc:117]: Its not clear here why the mask is only nlocs long, it makes it look as though it is only one mask per level in the data which isn't true since this is a time mask? Can we give some different names to some things?

**Comment by s-good** [comment]
> Interesting that you saw a CPP lint issue that wasnt picked up by the CI? maybe somehow when you ran cpplint it didn't pickup the configuration file? Regardless it all looks great to me! Do you want to take it out of draft, I will review and we can get it merged up?

I ran cpplint on the command line without a config file on the files that I had changed. It gave some errors about not indenting in a namespace. Let me know if you prefer the previous version as I can easily reverse my change.

**Comment by twsearle** [comment]
> > Interesting that you saw a CPP lint issue that wasnt picked up by the CI? maybe somehow when you ran cpplint it didn't pickup the configuration file? Regardless it all looks great to me! Do you want to take it out of draft, I will review and we can get it merged up?
> 
> I ran cpplint on the command line without a config file on the files that I had changed. It gave some errors about not indenting in a namespace. Let me know if you prefer the previous version as I can easily reverse my change.

if it passes the CI its fine by me. I think to use the configuration you need to run it starting from the root directory of the repo (the one containing `CPPLINT.cfg`). At least that is what the CI is doing, and it passed both before and after your change.

File: src/tests/orca-jedi/test_interpolator.cc (hunk 1 above)
Comment (s-good) [reply src/tests/orca-jedi/test_interpolator.cc:117]: I don't think it's a time mask in that way. I think it should be size nlocs and this is then updated at every time step. I.e. it first sets the mask to true to each observation that is closest to the time of the first model step and then runs the interpolation for that model time step. Then it goes on to the next model time step and updates the mask variable so that it is true for the observations that are closest to that time point and false for the others and so on. This is just what I managed to work out from the code, so it is possible that I misunderstood something.

**Comment by s-good** [comment]
> > > Interesting that you saw a CPP lint issue that wasnt picked up by the CI? maybe somehow when you ran cpplint it didn't pickup the configuration file? Regardless it all looks great to me! Do you want to take it out of draft, I will review and we can get it merged up?
> > 
> > 
> > I ran cpplint on the command line without a config file on the files that I had changed. It gave some errors about not indenting in a namespace. Let me know if you prefer the previous version as I can easily reverse my change.
> 
> if it passes the CI its fine by me. I think to use the configuration you need to run it starting from the root directory of the repo (the one containing `CPPLINT.cfg`). At least that is what the CI is doing, and it passed both before and after your change.

I investigated this and found that I was running a version of cpplint that is installed in one of the mobbs builds but the version that is run in the orca-jedi checks is in the orca-jedi repository and has the line that checks for incorrect indentation commented out: https://github.com/MetOffice/orca-jedi/blob/develop/tools/cpplint.py#L5963-L5964. If I uncomment this, there are 30 errors reported.

**Comment by s-good** [comment]
> Interesting that you saw a CPP lint issue that wasnt picked up by the CI? maybe somehow when you ran cpplint it didn't pickup the configuration file? Regardless it all looks great to me! Do you want to take it out of draft, I will review and we can get it merged up?

I've now marked this as ready for review.

File: src/tests/orca-jedi/test_interpolator.cc (hunk 1 above)
Comment (twsearle) [reply src/tests/orca-jedi/test_interpolator.cc:117]: Thanks sorry I just misunderstood!

**Review by twsearle — APPROVED** [review]
Great thanks looks good to me!
